{{- if not .Values.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.secretName" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $value := .Values.secretEnv }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
{{- end }}
