# Generated by Django 5.2.12 on 2026-03-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityJourneyReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "flow_type",
                    models.CharField(
                        choices=[("dm", "Direct Message"), ("video", "Video"), ("both", "Both")],
                        default="both",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("review", "In Review"), ("final", "Final")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("executive_summary", models.TextField(blank=True)),
                ("reality_check_answers", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_journey_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecurityJourneyStage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flow_type",
                    models.CharField(choices=[("dm", "Direct Message"), ("video", "Video")], max_length=16),
                ),
                ("stage_number", models.PositiveIntegerField()),
                ("stage_name", models.CharField(max_length=255)),
                ("component", models.CharField(blank=True, max_length=255)),
                ("protocol", models.CharField(blank=True, max_length=128)),
                ("security_assumptions", models.TextField(blank=True)),
                ("assets_exposed", models.TextField(blank=True)),
                ("trust_boundary", models.TextField(blank=True)),
                ("attack_surface", models.TextField(blank=True)),
                ("plaintext_data", models.TextField(blank=True)),
                ("encrypted_data", models.TextField(blank=True)),
                ("theoretically_readable_by", models.TextField(blank=True)),
                ("logs_should_exist", models.TextField(blank=True)),
                ("logs_must_not_contain", models.TextField(blank=True)),
                ("validation_method", models.TextField(blank=True)),
                ("likely_failure_modes", models.TextField(blank=True)),
                ("code_config_infra_checks", models.TextField(blank=True)),
                ("severity_if_compromised", models.CharField(blank=True, max_length=32)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="messenger.securityjourneyreport",
                    ),
                ),
            ],
            options={
                "ordering": ("flow_type", "stage_number", "id"),
                "unique_together": {("report", "flow_type", "stage_number", "stage_name")},
            },
        ),
        migrations.CreateModel(
            name="SecurityVerificationMatrixItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stage_label", models.CharField(blank=True, max_length=255)),
                ("expected_security_property", models.TextField()),
                ("evidence_source", models.TextField(blank=True)),
                ("how_to_test", models.TextField(blank=True)),
                ("pass_fail_criteria", models.TextField(blank=True)),
                ("common_misconfiguration", models.TextField(blank=True)),
                ("recommended_remediation", models.TextField(blank=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_items",
                        to="messenger.securityjourneyreport",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_items",
                        to="messenger.securityjourneystage",
                    ),
                ),
            ],
        ),
    ]
