# Generated by Django 5.2.12 on 2026-03-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0002_security_journey_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityLoggingFieldPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("field_name", models.CharField(max_length=128)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("allowed", "Allowed"),
                            ("hashed", "Hashed/Tokenized"),
                            ("redacted", "Redacted"),
                            ("forbidden", "Forbidden"),
                        ],
                        max_length=16,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logging_field_policies",
                        to="messenger.securityjourneyreport",
                    ),
                ),
            ],
            options={
                "ordering": ("field_name",),
                "unique_together": {("report", "field_name")},
            },
        ),
        migrations.CreateModel(
            name="SecurityThreatModelItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flow_type",
                    models.CharField(
                        choices=[("dm", "Direct Message"), ("video", "Video"), ("both", "Both")],
                        default="both",
                        max_length=16,
                    ),
                ),
                ("threat", models.CharField(max_length=255)),
                ("affected_stages", models.TextField(blank=True)),
                ("likely_indicators", models.TextField(blank=True)),
                ("controls", models.TextField(blank=True)),
                ("residual_risk", models.TextField(blank=True)),
                ("severity", models.CharField(blank=True, max_length=32)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threat_items",
                        to="messenger.securityjourneyreport",
                    ),
                ),
            ],
            options={
                "ordering": ("flow_type", "threat", "id"),
            },
        ),
    ]
