# Generated by Django 5.2.12 on 2026-03-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0003_stage3_logging_and_threat_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityGapItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rank", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("evidence", models.TextField(blank=True)),
                ("severity", models.CharField(blank=True, max_length=32)),
                ("recommended_remediation", models.TextField(blank=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gap_items",
                        to="messenger.securityjourneyreport",
                    ),
                ),
            ],
            options={
                "ordering": ("rank", "id"),
            },
        ),
        migrations.CreateModel(
            name="SecurityNextTestItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        default="medium",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("scope", models.CharField(blank=True, max_length=255)),
                ("method", models.TextField(blank=True)),
                ("pass_fail_criteria", models.TextField(blank=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_test_items",
                        to="messenger.securityjourneyreport",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "id"),
            },
        ),
    ]
