# Generated by Django 5.2.12 on 2026-03-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0005_stage5_audit_events"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityanalysisauditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("compiled_view", "Compiled Report Viewed"),
                    ("export", "Exported"),
                    ("snapshot_create", "Snapshot Created"),
                    ("retention_purge", "Retention Purge"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="SecurityReportSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "snapshot_format",
                    models.CharField(choices=[("json", "JSON")], default="json", max_length=16),
                ),
                ("payload", models.JSONField(default=dict)),
                ("payload_sha256", models.CharField(max_length=64)),
                ("notes", models.TextField(blank=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_report_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="messenger.securityjourneyreport",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
    ]
