# Generated by Django 5.2.12 on 2026-03-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0007_stage1_bootstrap_account_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityScopeCoverageItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("area", models.CharField(max_length=128)),
                ("present_in_implementation", models.BooleanField(default=False)),
                ("evidence", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scope_coverage_items",
                        to="messenger.securityjourneyreport",
                    ),
                ),
            ],
            options={
                "ordering": ("area", "id"),
                "unique_together": {("report", "area")},
            },
        ),
    ]
