# Generated by Django 5.2.12 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0008_stage2_scope_coverage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityanalysisauditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("run_triggered", "Analysis Run Triggered"),
                    ("compiled_view", "Compiled Report Viewed"),
                    ("export", "Exported"),
                    ("snapshot_create", "Snapshot Created"),
                    ("retention_purge", "Retention Purge"),
                ],
                max_length=32,
            ),
        ),
    ]
